---
- hosts: localhost
  tasks:
  - name: Testing DB to make sure it is available
    postgresql_db:
      state=present
      db={{ database_name }}
  - name: Run the first_names DB script
    shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/first_names.sql"
    register: psql_result
    failed_when: >
      psql_result.rc != 0
    changed_when: >
      psql_result.rc == 0 and ("INSERT 0 0" not in psql_result.stdout)
  - name: Run the last_names DB script
    shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/last_names.sql"
    register: psql_result
    failed_when: >
      psql_result.rc != 0
    changed_when: >
      psql_result.rc == 0 and ("INSERT 0 0" not in psql_result.stdout)
  - name: Run the functions DB script
    shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/functions.sql"
    register: psql_result
    failed_when: >
      psql_result.rc != 0
